---
- name: Construct repository address
  set_fact:
    containerd_repo_address: '{{ containerd_repo | regex_replace("/$", "") }}/{{ ansible_distribution | lower }}'
  when: containerd_repo_address is not defined

- name: "Set up package manager for {{ ansible_os_family }}"
  include_tasks: "config_{{ ansible_os_family }}.yml"

- name: Install containerd
  package:
    name:
      - "containerd.io"
  notify: restart containerd

- name: containerd configuration
  include_tasks: config_containerd.yml

- meta: flush_handlers

- name: Ensure containerd is started and enabled
  systemd:
    name: "containerd"
    enabled: true
    state: started
