---
- name: Construct repository address
  ansible.builtin.set_fact:
    containerd_repo_address: '{{ containerd_repo | regex_replace("/$", "") }}/{{ ansible_distribution | lower }}'
  when: containerd_repo_address is not defined

- name: "Set up package manager for {{ ansible_os_family }}"
  include_tasks: "config_{{ ansible_os_family }}.yml"

- name: Install containerd
  ansible.builtin.package:
    name:
      - "containerd.io"
  notify: restart containerd

- name: containerd configuration
  include_tasks: config_containerd.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Manage containerd cgroup
  block:
    - name: Set cgroup value in service file
      community.general.ini_file:
        path: /usr/lib/systemd/system/containerd.service
        section: Service
        option: Slice
        value: "{{ containerd_service_slice }}"
        mode: 0644
      register: slice_configuration

    - name: Restart containerd service
      ansible.builtin.systemd:
        name: containerd
        state: restarted
        daemon-reload: yes
      when: slice_configuration.changed
  when: containerd_service_slice is defined

- name: Ensure containerd is started and enabled
  ansible.builtin.systemd:
    name: "containerd"
    enabled: true
    state: started
