---
- name: Converge
  hosts: all
  tasks:
    - name: "Include containerd"
      include_role:
        name: "containerd"
      vars:
        containerd_registry_mirrors: "{{ lookup('env', 'CONTAINERD_MIRRORS') | from_json }}"
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'http_proxy') }}"
    HTTP_PROXY: "{{ lookup('env', 'HTTP_PROXY') }}"
    HTTPS_PROXY: "{{ lookup('env', 'HTTPS_PROXY') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
    NO_PROXY: "{{ lookup('env', 'NO_PROXY') }}"
