FROM base/{{ item.base }}:latest as configYum
FROM base/redhat:certs as configCerts

FROM {{ item.image }}

COPY --from=configYum / /
COPY --from=configCerts / /

RUN yum update -y && \
    yum install -y --setopt=tsflags=nodocs systemd python3 python3-devel python*-dnf sudo bash vim iproute && \ 
    rm -Rf /usr/share/doc && \
    rm -Rf /usr/share/man

RUN cd /lib/systemd/system/sysinit.target.wants/; \
    for i in *; do [ $i = systemd-tmpfiles-setup.service ] || rm -f $i; done

RUN rm -f /lib/systemd/system/multi-user.target.wants/* \
    /etc/systemd/system/*.wants/* \
    /lib/systemd/system/local-fs.target.wants/* \
    /lib/systemd/system/sockets.target.wants/*udev* \
    /lib/systemd/system/sockets.target.wants/*initctl* \
    /lib/systemd/system/basic.target.wants/* \
    /lib/systemd/system/anaconda.target.wants/*

VOLUME [ "/sys/fs/cgroup", "/tmp", "/run" ]

CMD [ "/usr/sbin/init" ]