---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: fedora
    box: fedora/32-cloud-base
    memory: 1024
    cpus: 1
  - name: centos7
    box: centos/7
    memory: 1024
    cpus: 1
  - name: debian
    box: debian/buster64
    memory: 1024
    cpus: 1
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
  log: true
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  directory: ../common/tests/
  lint:
    name: flake8
