---
- name: Prepare
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Installe les pré-requis python
      ansible.builtin.pip:
        executable: /usr/bin/pip3
        extra_args: --user
        requirements: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/requirements-test.txt"
